### ISSUE TITLE
how can i find

### ISSUE THREAD

**Issue by xzk49** [KhaosT/NTKExperimentalDigitalFaceBundleWatch#2]
NanoTimeKit.framework, RelevanceEngine.framework, and RelevanceEngineUI.framework
in xcode simulator file

**Comment by KhaosT** [comment]
They are under `/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks`.

**Comment by xzk49** [comment]
发自我的iPhone


------------------ Original ------------------
From: Khaos Tian ***@***.***&gt;
Date: Sun,Mar 13,2022 11:54 AM
To: KhaosT/NTKExperimentalDigitalFaceBundleWatch ***@***.***&gt;
Cc: xzk ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [KhaosT/NTKExperimentalDigitalFaceBundleWatch] how can i find (Issue #2)





 
They are under /Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/watchOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks.
